include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - android/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    unnecessary_lambdas: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    noop_primitive_operations: true
    use_super_parameters: true
    unnecessary_to_list_in_spreads: true
    avoid_void_async: true
    combinators_ordering: true
    dangling_library_doc_comments: true
    implicit_call_tearoffs: true
    unnecessary_null_aware_assignments: true
